mysql_host: serobon-2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38326138316364363337353665666338636362646135653733653261626530646636613733663336
          6136333938383038383930356362666335663635623835610a643331303432643164393361623730
          37633432353362633636343636646363663961376531386563656439346131363830366436663139
          3130306634613736310a373336306333303033663062306562646163386532373165323737393732
          39303437316637343830623237343432366664353066663234643531366334636662383232666661
          6564616430333537656666626131626132623437666437653661

dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

networks:
  - 192.168.42.0/23
  - 127.0.0.0/8

domain_name: swagla.pk 

exporter_user: exporter
exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61633935363131323930616566323531643131623837333765373463316233623664363564663535
          3562313963313834363531303063356662353635656633300a353034313032623935323662343265
          30656366356466613562643565613732303661323530343833636235663161336239313861623363
          6163316436313934360a643032646364373431326532343639656165643238316634316536333137
          63383261613233623931613537613962346639633938363366613732633537613731316335303162
          6265663332353437326634366561643261356432343938646666

grafana_user: serobon
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386533633762376136633234646639666461393135643037323633363430313434363837363535
          6232353931323532623335613237613136333633633761660a353766356463366163343361623936
          32383163343739643464336664346134653631393433393639613233343161633237643561373965
          6538336333303837370a613266313539373935666131343334616239356238386431363837396266
          64613331653733343062663736653961323661383737363231373331393131646465396230613861
          3239396361616134633364616665366438346536376566363634
